ISEC-estudantes/Lista-de-Repos

README.md

Corrigir alguns typos e falhas de formatação e adicionar repos minhas que tavam como privadas.

+ repos e correções

---

README.md

Novo material de POO, BD, SO, IRC, IIA

---

README.md

⠄⠄⠄⢰⣧⣼⣯⠄⣸⣠⣶⣶⣦⣾⠄⠄⠄⠄⡀⠄⢀⣿⣿⠄⠄⠄⢸⡇⠄⠄
⠄⠄⠄⣾⣿⠿⠿⠶⠿⢿⣿⣿⣿⣿⣦⣤⣄⢀⡅⢠⣾⣛⡉⠄⠄⠄⠸⢀⣿⠄
⠄⠄⢀⡋⣡⣴⣶⣶⡀⠄⠄⠙⢿⣿⣿⣿⣿⣿⣴⣿⣿⣿⢃⣤⣄⣀⣥⣿⣿⠄
⠄⠄⢸⣇⠻⣿⣿⣿⣧⣀⢀⣠⡌⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠿⣿⣿⣿⠄
⠄⢀⢸⣿⣷⣤⣤⣤⣬⣙⣛⢿⣿⣿⣿⣿⣿⣿⡿⣿⣿⡍⠄⠄⢀⣤⣄⠉⠋⣰
⠄⣼⣖⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⢇⣿⣿⡷⠶⠶⢿⣿⣿⠇⢀⣤
⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣿⣿⣿⡇⣿⣿⣿⣿⣿⣿⣷⣶⣥⣴⣿⡗
⢀⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠄
⢸⣿⣦⣌⣛⣻⣿⣿⣧⠙⠛⠛⡭⠅⠒⠦⠭⣭⡻⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠄
⠘⣿⣿⣿⣿⣿⣿⣿⣿⡆⠄⠄⠄⠄⠄⠄⠄⠄⠹⠈⢋⣽⣿⣿⣿⣿⣵⣾⠃⠄
⠄⠘⣿⣿⣿⣿⣿⣿⣿⣿⠄⣴⣿⣶⣄⠄⣴⣶⠄⢀⣾⣿⣿⣿⣿⣿⣿⠃⠄⠄
⠄⠄⠈⠻⣿⣿⣿⣿⣿⣿⡄⢻⣿⣿⣿⠄⣿⣿⡀⣾⣿⣿⣿⣿⣛⠛⠁⠄⠄⠄
⠄⠄⠄⠄⠈⠛⢿⣿⣿⣿⠁⠞⢿⣿⣿⡄⢿⣿⡇⣸⣿⣿⠿⠛⠁⠄⠄⠄⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠉⠻⣿⣿⣾⣦⡙⠻⣷⣾⣿⠃⠿⠋⠁⠄⠄⠄⠄⠄⢀⣠⣴
⣿⣿⣿⣶⣶⣮⣥⣒⠲⢮⣝⡿⣿⣿⡆⣿⡿⠃⠄⠄⠄⠄⠄⠄⠄⣠⣴⣿⣿⣿

OnikenX-senpai aceita

---

README.md

- [EstruturasDeDados] by DanielMoreiraRibeiro added;
- [MyHigherEducationExperience] by DanielMoreiraRibeiro added;

2 more links added

---

README.md

trabalho de bd

---

README.md

New category (SO2 - Sistemas Operativos II) added

---

README.md

New link about "Recursos" inside "SO2 - Sistemas Operativos II" added

Link to "SistemasOperativosII-LEI-ISEC" added

---

README.md

New link about "Recursos" inside "SO - Sistemas Operativos" added

Link to "SistemasOperativos-LEI-ISEC" added

---

README.md

New link about "Recursos" inside "PA - Programação Avançada" added

Link to "ProgramacaoAvancada-LEI-ISEC" added

---

README.md

New link about "Recursos" inside "PD - Programação Distribuída" added

Link to "ProgramacaoDistribuida-LEI-ISEC" added

---

README.md

New link about "Recursos" inside "AMOV - Arquiteturas Móveis" added

Link to "ArquiteturasMoveis-LEI-ISEC" added

---

README.md

Reason for deletion: expired link / repository is not available anymore.

deletion of expired links

---

README.md

MEDICALso by @zmiguel and @dsemiao 2021/2022

Add MEDICALso

---

README.md

plus um trabalho de BD deste ano

Adicionei LS e fichas práticas das aulas

---

README.md

Adicionei o trabalho prático de ID (Integração de dados) 2º ano 2º semestre do ramo de SI.
Fiz 3 commits para arranjar o click.

Adicionar TP de ID

---

README.md

Para além disso criei um espaço para a disciplina de AABD específica do ramo de SI, quando saírem as notas depois meto lá o trabalho

Fichas Práticas de BD e AABD 21/22

---

README.md

Adicionei o TP de P

---

README.md

add TP - Programacao

---

README.md

Adicionei os Trabalho de TWEB,LS,TAC 2022/2023...

Adicionei Trabalho de TWEB,LS,TAC 2022/2023

---

README.md

Estou a dar update à lista de repos do ISEC com os materiais que acumulei durante os três anos do meu curso de Licenciatura em Engenharia Informática.

Update Lista de Repos com os meus materiais

---

README.md

A Lista de Repos estava desformatada, com títulos sem links, parágrafos mal feitos, etc... 
Corrigi tudo o que vi.

Reformatar Lista de Repos do ISEC
